name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  rubocop:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 16
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: make test
